//Point

var PEN_THICKNESS_GIVEN_POINT = 0;
var PEN_THICKNESS_ACTIVE_POINT = 18;
var PEN_THICKNESS_DRAWN_POINT = 6;
var PEN_THICKNESS_SOLUTION_POINT = 15;

//Path

var PEN_THICKNESS_GIVEN_PATH = 1;
var PEN_THICKNESS_ACTIVE_PATH = 3;
var PEN_THICKNESS_DRAWN_PATH = 1;
var PEN_THICKNESS_SOLUTION_PATH = 5;

//Color

var BACKGROUND_COLOR = "hsl(201, 69%, 25%)";

var PEN_COLOR_GIVEN = "hsl(0, 0%, 80%)";
var PEN_COLOR_ACTIVE = "hsl(201, 69%, 90%)";
var PEN_COLOR_DRAWN = "hsl(201, 20%, 55%)";
var PEN_COLOR_SOLUTION = "hsl(0, 0%, 0%)";

//Animation

const DELAY_START = 300;
const DELAY_MID = 200;
const DELAY_END = 2000;

const DURATION_POINT = 300;
const DURATION_PATH = 300;
const DURATION_FADE = 500;